### PR TITLE
Adds the readme file

### PR DESCRIPTION
**Pull request by aivascu**
- Defines the prerequisite necessary to work on documentation
- Describes the setup process
- Describes the documentation debug
- Describes solution to issues encountered while setting up the local environment

### CODE REVIEW

**Comment by zvirja** [comment]
Nice readme, cool that you figured it out.

In order to simplify things, did you consider also having docker ENV for this? I see it like we have `Dockerfile` where we configure the linux based env, so that it does not matter what we have installed locally. Then when we would like to compile/watch it locally, we could run a special script which runs docker container which watches FS for changes and proxies entry URL back.

Not sure whether you find it useful for yourself, but it's just insane to have local build that complicated 😟 I also remember struggling with that, especially when I needed to work with different repositories using different version of ruby/jekyll.

**Review by zvirja — APPROVED** [review]

**Comment by aivascu** [comment]
@zvirja that's a really cool idea! 
I didn't consider Docker as an option for the environment, but now that you mentioned it sounds great. I'll definitely try it out. 
Thanks! 🙂

**Comment by zvirja** [comment]
@aivascu As a starting point you can be inspired by [VS Code Container Development](https://code.visualstudio.com/docs/remote/containers). Here is an example of project for .NET: https://github.com/microsoft/vscode-remote-try-dotnetcore (you can also find it for other projects).

In this case we probably don't need to develop in container, as no special tooling is required to modify markup files. But you can be inspired by the concepts and how smooth it works:

- mount current directory to container as a volume
- forward port out of container when run in watch mode

**Comment by aivascu** [comment]
@zvirja I believe I don't have access to merge PRs in this repository. Could you merge the PRs or add me as a maintainer to this repository as well?

**Comment by zvirja** [comment]
@aivascu I gave you access, try again 😉

**Pull request merged**
